#!/bin/bash

#USAGE: runAllScripts [-m|-M numMasters] [-w|-W numWorkers (per Master)]
# 	[-c|-C numClients]

#Defaults:
numMasters=1
numWorkers=1
numClients=1

#Options:
while [[ $# > 1 ]]
do
opt="$1"
shift

case $opt in
    -m|-M)
    numMasters="$1"
    shift
    ;;
    -w|-W)
    numWorkers="$1"
    shift
    ;;
    -c|-C)
    numClients="$1"
    shift
    ;;
    *)
            # unknown option
    ;;
esac
done


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Using $numMasters Masters."
echo "Using $numWorkers Workers per Master."
echo "Total of $numClients Clients will call in."

Client2Master=4500
Client2LB=7500
Equalizer2Master=5500
LB_HN=127.0.0.1
M_HN=127.0.0.1
Master2LB=6500

cd "${DIR}/LoadBalancer/out"
gnome-terminal -x bash -c "java LoadBalancer ${Client2LB} ${Master2LB};bash"

for (( i = 0; i < ${numMasters}; i++))
do
	C2M=$(( ${Client2Master} + ${i} ))
	E2M=$(( ${Equalizer2Master} + ${i} ))

	cd "${DIR}/Master/out"
	gnome-terminal -x bash -c "java -classpath ../sigar.jar:. TwoListeners ${C2M} ${E2M} ${LB_HN} ${Master2LB}"

	for (( j = 0; j<${numWorkers}; j++))
	do
		cd "${DIR}/Equalizer/out"
		gnome-terminal -x bash -c "java Equalizers ${M_HN} ${E2M}"
	done

done


for (( i = 0; i<${numClients}; i++))
do
    sleep 3
	cd "${DIR}/Client/out"
    echo "HERE"
	command="java CloudImageClient ${LB_HN} ${Client2LB} ../imDir NewStuff_${i}"
	#gnome-terminal -x bash -c "export utime=$( TIMEFORMAT='%E';time (${command}) 2>&1 1>/dev/null );echo ${utime} > TEST_${i}; nc localhost 1200 < TEST_${i}"
    gnome-terminal -x bash -c " echo $( TIMEFORMAT='%E';time (${command}) 2>&1 1>/dev/null ) > TEST_${i}"

done

total=0
for (( i = 0; i<${numClients}; i++))
do

    cd "${DIR}/Client/out"

    #new=$( nc -l 1200 )
    new=$( cat TEST_${i} )
    total=$( bc <<< "${total} + ${new}" )
done

echo $total